# Generated by Django 5.0.4 on 2024-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postbook",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
